version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused code

    # Additional linters
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security-focused linter
    - gocritic      # Provides diagnostics that check for bugs
    - gocyclo       # Compute cyclomatic complexity
    - dupl          # Code duplication detection
    - prealloc      # Find slice declarations that could be preallocated
    - noctx         # Find HTTP requests without context
    - bodyclose     # Check for HTTP response body close
    - errorlint     # Find code that will cause problems with Go 1.13+ error wrapping
    - goconst       # Find repeated strings that could be constants
    - copyloopvar   # Check for loop variable copies (replaces exportloopref)

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  gosec:
    excludes:
      - G204  # Audit use of command execution
      - G304  # File path provided as taint input

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - commentFormatting
      - whyNoLint

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude known issues in generated code
    - path: ".*\\.pb\\.go"
      linters:
        - all

    # Exclude issues with function length in tests
    - path: _test\.go
      text: "Function 'Test.*' is too long"
      linters:
        - revive

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
