run:
  timeout: 5m

linters:
  enable:
    - govet
  disable:
    - errcheck
    - staticcheck
    - unused
    - ineffassign

linters-settings:
  govet:
    disable:
      - shadow
      - fieldalignment

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
