// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/kv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRequest contains the key to retrieve
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// If true, ensures linearizable read from leader
	Consistent    bool `protobuf:"varint,2,opt,name=consistent,proto3" json:"consistent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetConsistent() bool {
	if x != nil {
		return x.Consistent
	}
	return false
}

// GetResponse contains the retrieved value
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Value []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	// If read from follower, indicates potential staleness
	FromLeader    bool `protobuf:"varint,3,opt,name=from_leader,json=fromLeader,proto3" json:"from_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_proto_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetFromLeader() bool {
	if x != nil {
		return x.FromLeader
	}
	return false
}

// PutRequest contains the key-value pair to store
type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_api_proto_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// PutResponse confirms the put operation
type PutResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// The leader that processed the request
	Leader        string `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_api_proto_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PutResponse) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

// DeleteRequest contains the key to delete
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// DeleteResponse confirms the delete operation
type DeleteResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// The leader that processed the request
	Leader        string `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeleteResponse) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

// ListRequest contains parameters for listing keys
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Max number of keys to return (0 = all)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_proto_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListResponse contains the matching keys
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // Total matching keys (may be > len(keys) if limited)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_proto_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// StatsRequest requests store statistics
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_api_proto_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{8}
}

// StatsResponse contains store statistics
type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyCount      uint64                 `protobuf:"varint,1,opt,name=key_count,json=keyCount,proto3" json:"key_count,omitempty"`
	GetCount      uint64                 `protobuf:"varint,2,opt,name=get_count,json=getCount,proto3" json:"get_count,omitempty"`
	PutCount      uint64                 `protobuf:"varint,3,opt,name=put_count,json=putCount,proto3" json:"put_count,omitempty"`
	DeleteCount   uint64                 `protobuf:"varint,4,opt,name=delete_count,json=deleteCount,proto3" json:"delete_count,omitempty"`
	RaftState     string                 `protobuf:"bytes,5,opt,name=raft_state,json=raftState,proto3" json:"raft_state,omitempty"` // "Leader", "Follower", "Candidate"
	RaftLeader    string                 `protobuf:"bytes,6,opt,name=raft_leader,json=raftLeader,proto3" json:"raft_leader,omitempty"`
	RaftTerm      uint64                 `protobuf:"varint,7,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	RaftLastIndex uint64                 `protobuf:"varint,8,opt,name=raft_last_index,json=raftLastIndex,proto3" json:"raft_last_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_proto_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{9}
}

func (x *StatsResponse) GetKeyCount() uint64 {
	if x != nil {
		return x.KeyCount
	}
	return 0
}

func (x *StatsResponse) GetGetCount() uint64 {
	if x != nil {
		return x.GetCount
	}
	return 0
}

func (x *StatsResponse) GetPutCount() uint64 {
	if x != nil {
		return x.PutCount
	}
	return 0
}

func (x *StatsResponse) GetDeleteCount() uint64 {
	if x != nil {
		return x.DeleteCount
	}
	return 0
}

func (x *StatsResponse) GetRaftState() string {
	if x != nil {
		return x.RaftState
	}
	return ""
}

func (x *StatsResponse) GetRaftLeader() string {
	if x != nil {
		return x.RaftLeader
	}
	return ""
}

func (x *StatsResponse) GetRaftTerm() uint64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

func (x *StatsResponse) GetRaftLastIndex() uint64 {
	if x != nil {
		return x.RaftLastIndex
	}
	return 0
}

// LeaderRequest requests the current leader
type LeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderRequest) Reset() {
	*x = LeaderRequest{}
	mi := &file_api_proto_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderRequest) ProtoMessage() {}

func (x *LeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderRequest.ProtoReflect.Descriptor instead.
func (*LeaderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{10}
}

// LeaderResponse contains the current leader information
type LeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddress string                 `protobuf:"bytes,2,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	IsLeader      bool                   `protobuf:"varint,3,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"` // True if this node is the leader
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderResponse) Reset() {
	*x = LeaderResponse{}
	mi := &file_api_proto_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderResponse) ProtoMessage() {}

func (x *LeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderResponse.ProtoReflect.Descriptor instead.
func (*LeaderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{11}
}

func (x *LeaderResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *LeaderResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

func (x *LeaderResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

var File_api_proto_kv_proto protoreflect.FileDescriptor

const file_api_proto_kv_proto_rawDesc = "" +
	"\n" +
	"\x12api/proto/kv.proto\x12\akvstore\">\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"consistent\x18\x02 \x01(\bR\n" +
	"consistent\"Z\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x1f\n" +
	"\vfrom_leader\x18\x03 \x01(\bR\n" +
	"fromLeader\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"U\n" +
	"\vPutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\tR\x06leader\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"X\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\tR\x06leader\";\n" +
	"\vListRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"8\n" +
	"\fListResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x0e\n" +
	"\fStatsRequest\"\x8e\x02\n" +
	"\rStatsResponse\x12\x1b\n" +
	"\tkey_count\x18\x01 \x01(\x04R\bkeyCount\x12\x1b\n" +
	"\tget_count\x18\x02 \x01(\x04R\bgetCount\x12\x1b\n" +
	"\tput_count\x18\x03 \x01(\x04R\bputCount\x12!\n" +
	"\fdelete_count\x18\x04 \x01(\x04R\vdeleteCount\x12\x1d\n" +
	"\n" +
	"raft_state\x18\x05 \x01(\tR\traftState\x12\x1f\n" +
	"\vraft_leader\x18\x06 \x01(\tR\n" +
	"raftLeader\x12\x1b\n" +
	"\traft_term\x18\a \x01(\x04R\braftTerm\x12&\n" +
	"\x0fraft_last_index\x18\b \x01(\x04R\rraftLastIndex\"\x0f\n" +
	"\rLeaderRequest\"q\n" +
	"\x0eLeaderResponse\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\x12%\n" +
	"\x0eleader_address\x18\x02 \x01(\tR\rleaderAddress\x12\x1b\n" +
	"\tis_leader\x18\x03 \x01(\bR\bisLeader2\xd6\x02\n" +
	"\aKVStore\x120\n" +
	"\x03Get\x12\x13.kvstore.GetRequest\x1a\x14.kvstore.GetResponse\x120\n" +
	"\x03Put\x12\x13.kvstore.PutRequest\x1a\x14.kvstore.PutResponse\x129\n" +
	"\x06Delete\x12\x16.kvstore.DeleteRequest\x1a\x17.kvstore.DeleteResponse\x123\n" +
	"\x04List\x12\x14.kvstore.ListRequest\x1a\x15.kvstore.ListResponse\x129\n" +
	"\bGetStats\x12\x15.kvstore.StatsRequest\x1a\x16.kvstore.StatsResponse\x12<\n" +
	"\tGetLeader\x12\x16.kvstore.LeaderRequest\x1a\x17.kvstore.LeaderResponseB/Z-github.com/RashikAnsar/raftkv/api/proto;protob\x06proto3"

var (
	file_api_proto_kv_proto_rawDescOnce sync.Once
	file_api_proto_kv_proto_rawDescData []byte
)

func file_api_proto_kv_proto_rawDescGZIP() []byte {
	file_api_proto_kv_proto_rawDescOnce.Do(func() {
		file_api_proto_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_kv_proto_rawDesc), len(file_api_proto_kv_proto_rawDesc)))
	})
	return file_api_proto_kv_proto_rawDescData
}

var file_api_proto_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_kv_proto_goTypes = []any{
	(*GetRequest)(nil),     // 0: kvstore.GetRequest
	(*GetResponse)(nil),    // 1: kvstore.GetResponse
	(*PutRequest)(nil),     // 2: kvstore.PutRequest
	(*PutResponse)(nil),    // 3: kvstore.PutResponse
	(*DeleteRequest)(nil),  // 4: kvstore.DeleteRequest
	(*DeleteResponse)(nil), // 5: kvstore.DeleteResponse
	(*ListRequest)(nil),    // 6: kvstore.ListRequest
	(*ListResponse)(nil),   // 7: kvstore.ListResponse
	(*StatsRequest)(nil),   // 8: kvstore.StatsRequest
	(*StatsResponse)(nil),  // 9: kvstore.StatsResponse
	(*LeaderRequest)(nil),  // 10: kvstore.LeaderRequest
	(*LeaderResponse)(nil), // 11: kvstore.LeaderResponse
}
var file_api_proto_kv_proto_depIdxs = []int32{
	0,  // 0: kvstore.KVStore.Get:input_type -> kvstore.GetRequest
	2,  // 1: kvstore.KVStore.Put:input_type -> kvstore.PutRequest
	4,  // 2: kvstore.KVStore.Delete:input_type -> kvstore.DeleteRequest
	6,  // 3: kvstore.KVStore.List:input_type -> kvstore.ListRequest
	8,  // 4: kvstore.KVStore.GetStats:input_type -> kvstore.StatsRequest
	10, // 5: kvstore.KVStore.GetLeader:input_type -> kvstore.LeaderRequest
	1,  // 6: kvstore.KVStore.Get:output_type -> kvstore.GetResponse
	3,  // 7: kvstore.KVStore.Put:output_type -> kvstore.PutResponse
	5,  // 8: kvstore.KVStore.Delete:output_type -> kvstore.DeleteResponse
	7,  // 9: kvstore.KVStore.List:output_type -> kvstore.ListResponse
	9,  // 10: kvstore.KVStore.GetStats:output_type -> kvstore.StatsResponse
	11, // 11: kvstore.KVStore.GetLeader:output_type -> kvstore.LeaderResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_kv_proto_init() }
func file_api_proto_kv_proto_init() {
	if File_api_proto_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_kv_proto_rawDesc), len(file_api_proto_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_kv_proto_goTypes,
		DependencyIndexes: file_api_proto_kv_proto_depIdxs,
		MessageInfos:      file_api_proto_kv_proto_msgTypes,
	}.Build()
	File_api_proto_kv_proto = out.File
	file_api_proto_kv_proto_goTypes = nil
	file_api_proto_kv_proto_depIdxs = nil
}
