// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/proto/kv.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KVStore_Get_FullMethodName                = "/kvstore.KVStore/Get"
	KVStore_Put_FullMethodName                = "/kvstore.KVStore/Put"
	KVStore_Delete_FullMethodName             = "/kvstore.KVStore/Delete"
	KVStore_List_FullMethodName               = "/kvstore.KVStore/List"
	KVStore_CompareAndSwap_FullMethodName     = "/kvstore.KVStore/CompareAndSwap"
	KVStore_GetWithVersion_FullMethodName     = "/kvstore.KVStore/GetWithVersion"
	KVStore_GetStats_FullMethodName           = "/kvstore.KVStore/GetStats"
	KVStore_GetLeader_FullMethodName          = "/kvstore.KVStore/GetLeader"
	KVStore_GetLeadershipInfo_FullMethodName  = "/kvstore.KVStore/GetLeadershipInfo"
	KVStore_Stepdown_FullMethodName           = "/kvstore.KVStore/Stepdown"
	KVStore_TransferLeadership_FullMethodName = "/kvstore.KVStore/TransferLeadership"
	KVStore_GetElectionHistory_FullMethodName = "/kvstore.KVStore/GetElectionHistory"
	KVStore_GetTTL_FullMethodName             = "/kvstore.KVStore/GetTTL"
	KVStore_SetTTL_FullMethodName             = "/kvstore.KVStore/SetTTL"
	KVStore_Watch_FullMethodName              = "/kvstore.KVStore/Watch"
)

// KVStoreClient is the client API for KVStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KVStore service provides high-performance RPC for key-value operations
type KVStoreClient interface {
	// Get retrieves the value for a given key
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Put stores a key-value pair
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	// Delete removes a key-value pair
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// List returns keys matching a prefix
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// CompareAndSwap atomically updates a key if the version matches
	CompareAndSwap(ctx context.Context, in *CompareAndSwapRequest, opts ...grpc.CallOption) (*CompareAndSwapResponse, error)
	// GetWithVersion retrieves the value and version for a key
	GetWithVersion(ctx context.Context, in *GetWithVersionRequest, opts ...grpc.CallOption) (*GetWithVersionResponse, error)
	// GetStats returns store statistics
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// GetLeader returns the current Raft leader
	GetLeader(ctx context.Context, in *LeaderRequest, opts ...grpc.CallOption) (*LeaderResponse, error)
	// GetLeadershipInfo returns detailed leadership information
	GetLeadershipInfo(ctx context.Context, in *LeadershipInfoRequest, opts ...grpc.CallOption) (*LeadershipInfoResponse, error)
	// Stepdown forces the leader to step down
	Stepdown(ctx context.Context, in *StepdownRequest, opts ...grpc.CallOption) (*StepdownResponse, error)
	// TransferLeadership transfers leadership to a specific node
	TransferLeadership(ctx context.Context, in *TransferLeadershipRequest, opts ...grpc.CallOption) (*TransferLeadershipResponse, error)
	// GetElectionHistory returns the history of leadership changes
	GetElectionHistory(ctx context.Context, in *ElectionHistoryRequest, opts ...grpc.CallOption) (*ElectionHistoryResponse, error)
	// GetTTL returns the remaining TTL for a key
	GetTTL(ctx context.Context, in *GetTTLRequest, opts ...grpc.CallOption) (*GetTTLResponse, error)
	// SetTTL updates the TTL for an existing key
	SetTTL(ctx context.Context, in *SetTTLRequest, opts ...grpc.CallOption) (*SetTTLResponse, error)
	// Watch subscribes to real-time key-value change notifications
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
}

type kVStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewKVStoreClient(cc grpc.ClientConnInterface) KVStoreClient {
	return &kVStoreClient{cc}
}

func (c *kVStoreClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, KVStore_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, KVStore_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, KVStore_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, KVStore_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) CompareAndSwap(ctx context.Context, in *CompareAndSwapRequest, opts ...grpc.CallOption) (*CompareAndSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareAndSwapResponse)
	err := c.cc.Invoke(ctx, KVStore_CompareAndSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) GetWithVersion(ctx context.Context, in *GetWithVersionRequest, opts ...grpc.CallOption) (*GetWithVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithVersionResponse)
	err := c.cc.Invoke(ctx, KVStore_GetWithVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, KVStore_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) GetLeader(ctx context.Context, in *LeaderRequest, opts ...grpc.CallOption) (*LeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaderResponse)
	err := c.cc.Invoke(ctx, KVStore_GetLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) GetLeadershipInfo(ctx context.Context, in *LeadershipInfoRequest, opts ...grpc.CallOption) (*LeadershipInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeadershipInfoResponse)
	err := c.cc.Invoke(ctx, KVStore_GetLeadershipInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) Stepdown(ctx context.Context, in *StepdownRequest, opts ...grpc.CallOption) (*StepdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepdownResponse)
	err := c.cc.Invoke(ctx, KVStore_Stepdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) TransferLeadership(ctx context.Context, in *TransferLeadershipRequest, opts ...grpc.CallOption) (*TransferLeadershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferLeadershipResponse)
	err := c.cc.Invoke(ctx, KVStore_TransferLeadership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) GetElectionHistory(ctx context.Context, in *ElectionHistoryRequest, opts ...grpc.CallOption) (*ElectionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ElectionHistoryResponse)
	err := c.cc.Invoke(ctx, KVStore_GetElectionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) GetTTL(ctx context.Context, in *GetTTLRequest, opts ...grpc.CallOption) (*GetTTLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTTLResponse)
	err := c.cc.Invoke(ctx, KVStore_GetTTL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) SetTTL(ctx context.Context, in *SetTTLRequest, opts ...grpc.CallOption) (*SetTTLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTTLResponse)
	err := c.cc.Invoke(ctx, KVStore_SetTTL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KVStore_ServiceDesc.Streams[0], KVStore_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KVStore_WatchClient = grpc.ServerStreamingClient[WatchEvent]

// KVStoreServer is the server API for KVStore service.
// All implementations must embed UnimplementedKVStoreServer
// for forward compatibility.
//
// KVStore service provides high-performance RPC for key-value operations
type KVStoreServer interface {
	// Get retrieves the value for a given key
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Put stores a key-value pair
	Put(context.Context, *PutRequest) (*PutResponse, error)
	// Delete removes a key-value pair
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// List returns keys matching a prefix
	List(context.Context, *ListRequest) (*ListResponse, error)
	// CompareAndSwap atomically updates a key if the version matches
	CompareAndSwap(context.Context, *CompareAndSwapRequest) (*CompareAndSwapResponse, error)
	// GetWithVersion retrieves the value and version for a key
	GetWithVersion(context.Context, *GetWithVersionRequest) (*GetWithVersionResponse, error)
	// GetStats returns store statistics
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	// GetLeader returns the current Raft leader
	GetLeader(context.Context, *LeaderRequest) (*LeaderResponse, error)
	// GetLeadershipInfo returns detailed leadership information
	GetLeadershipInfo(context.Context, *LeadershipInfoRequest) (*LeadershipInfoResponse, error)
	// Stepdown forces the leader to step down
	Stepdown(context.Context, *StepdownRequest) (*StepdownResponse, error)
	// TransferLeadership transfers leadership to a specific node
	TransferLeadership(context.Context, *TransferLeadershipRequest) (*TransferLeadershipResponse, error)
	// GetElectionHistory returns the history of leadership changes
	GetElectionHistory(context.Context, *ElectionHistoryRequest) (*ElectionHistoryResponse, error)
	// GetTTL returns the remaining TTL for a key
	GetTTL(context.Context, *GetTTLRequest) (*GetTTLResponse, error)
	// SetTTL updates the TTL for an existing key
	SetTTL(context.Context, *SetTTLRequest) (*SetTTLResponse, error)
	// Watch subscribes to real-time key-value change notifications
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	mustEmbedUnimplementedKVStoreServer()
}

// UnimplementedKVStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKVStoreServer struct{}

func (UnimplementedKVStoreServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKVStoreServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedKVStoreServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKVStoreServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedKVStoreServer) CompareAndSwap(context.Context, *CompareAndSwapRequest) (*CompareAndSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompareAndSwap not implemented")
}
func (UnimplementedKVStoreServer) GetWithVersion(context.Context, *GetWithVersionRequest) (*GetWithVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithVersion not implemented")
}
func (UnimplementedKVStoreServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedKVStoreServer) GetLeader(context.Context, *LeaderRequest) (*LeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeader not implemented")
}
func (UnimplementedKVStoreServer) GetLeadershipInfo(context.Context, *LeadershipInfoRequest) (*LeadershipInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeadershipInfo not implemented")
}
func (UnimplementedKVStoreServer) Stepdown(context.Context, *StepdownRequest) (*StepdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stepdown not implemented")
}
func (UnimplementedKVStoreServer) TransferLeadership(context.Context, *TransferLeadershipRequest) (*TransferLeadershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferLeadership not implemented")
}
func (UnimplementedKVStoreServer) GetElectionHistory(context.Context, *ElectionHistoryRequest) (*ElectionHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetElectionHistory not implemented")
}
func (UnimplementedKVStoreServer) GetTTL(context.Context, *GetTTLRequest) (*GetTTLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTTL not implemented")
}
func (UnimplementedKVStoreServer) SetTTL(context.Context, *SetTTLRequest) (*SetTTLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTTL not implemented")
}
func (UnimplementedKVStoreServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedKVStoreServer) mustEmbedUnimplementedKVStoreServer() {}
func (UnimplementedKVStoreServer) testEmbeddedByValue()                 {}

// UnsafeKVStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KVStoreServer will
// result in compilation errors.
type UnsafeKVStoreServer interface {
	mustEmbedUnimplementedKVStoreServer()
}

func RegisterKVStoreServer(s grpc.ServiceRegistrar, srv KVStoreServer) {
	// If the following call pancis, it indicates UnimplementedKVStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KVStore_ServiceDesc, srv)
}

func _KVStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_CompareAndSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareAndSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).CompareAndSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_CompareAndSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).CompareAndSwap(ctx, req.(*CompareAndSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_GetWithVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).GetWithVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_GetWithVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).GetWithVersion(ctx, req.(*GetWithVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_GetLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).GetLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_GetLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).GetLeader(ctx, req.(*LeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_GetLeadershipInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeadershipInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).GetLeadershipInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_GetLeadershipInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).GetLeadershipInfo(ctx, req.(*LeadershipInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_Stepdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).Stepdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_Stepdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).Stepdown(ctx, req.(*StepdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_TransferLeadership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferLeadershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).TransferLeadership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_TransferLeadership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).TransferLeadership(ctx, req.(*TransferLeadershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_GetElectionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElectionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).GetElectionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_GetElectionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).GetElectionHistory(ctx, req.(*ElectionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_GetTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).GetTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_GetTTL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).GetTTL(ctx, req.(*GetTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_SetTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).SetTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_SetTTL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).SetTTL(ctx, req.(*SetTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KVStoreServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KVStore_WatchServer = grpc.ServerStreamingServer[WatchEvent]

// KVStore_ServiceDesc is the grpc.ServiceDesc for KVStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KVStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvstore.KVStore",
	HandlerType: (*KVStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KVStore_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _KVStore_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KVStore_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _KVStore_List_Handler,
		},
		{
			MethodName: "CompareAndSwap",
			Handler:    _KVStore_CompareAndSwap_Handler,
		},
		{
			MethodName: "GetWithVersion",
			Handler:    _KVStore_GetWithVersion_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _KVStore_GetStats_Handler,
		},
		{
			MethodName: "GetLeader",
			Handler:    _KVStore_GetLeader_Handler,
		},
		{
			MethodName: "GetLeadershipInfo",
			Handler:    _KVStore_GetLeadershipInfo_Handler,
		},
		{
			MethodName: "Stepdown",
			Handler:    _KVStore_Stepdown_Handler,
		},
		{
			MethodName: "TransferLeadership",
			Handler:    _KVStore_TransferLeadership_Handler,
		},
		{
			MethodName: "GetElectionHistory",
			Handler:    _KVStore_GetElectionHistory_Handler,
		},
		{
			MethodName: "GetTTL",
			Handler:    _KVStore_GetTTL_Handler,
		},
		{
			MethodName: "SetTTL",
			Handler:    _KVStore_SetTTL_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _KVStore_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/kv.proto",
}
