// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/queue.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message represents a queue message
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`       // Unix timestamp in milliseconds
	ScheduledAt   int64                  `protobuf:"varint,7,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"` // Unix timestamp in milliseconds (0 = not scheduled)
	ExpiresAt     int64                  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`       // Unix timestamp in milliseconds (0 = no expiration)
	DeliveryCount int32                  `protobuf:"varint,9,opt,name=delivery_count,json=deliveryCount,proto3" json:"delivery_count,omitempty"`
	LastDelivered int64                  `protobuf:"varint,10,opt,name=last_delivered,json=lastDelivered,proto3" json:"last_delivered,omitempty"` // Unix timestamp in milliseconds (0 = never delivered)
	DlqReason     string                 `protobuf:"bytes,11,opt,name=dlq_reason,json=dlqReason,proto3" json:"dlq_reason,omitempty"`              // Reason for DLQ (empty if not in DLQ)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proto_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *Message) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Message) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *Message) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Message) GetDeliveryCount() int32 {
	if x != nil {
		return x.DeliveryCount
	}
	return 0
}

func (x *Message) GetLastDelivered() int64 {
	if x != nil {
		return x.LastDelivered
	}
	return 0
}

func (x *Message) GetDlqReason() string {
	if x != nil {
		return x.DlqReason
	}
	return ""
}

// QueueConfig represents queue configuration
type QueueConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                                             // "fifo" or "priority"
	MaxLength           int32                  `protobuf:"varint,3,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`                                 // 0 = unlimited
	MaxRetries          int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`                              // 0 = unlimited
	MessageTtlMs        int64                  `protobuf:"varint,5,opt,name=message_ttl_ms,json=messageTtlMs,proto3" json:"message_ttl_ms,omitempty"`                      // Message TTL in milliseconds (0 = no expiration)
	VisibilityTimeoutMs int64                  `protobuf:"varint,6,opt,name=visibility_timeout_ms,json=visibilityTimeoutMs,proto3" json:"visibility_timeout_ms,omitempty"` // Visibility timeout in milliseconds
	DlqEnabled          bool                   `protobuf:"varint,7,opt,name=dlq_enabled,json=dlqEnabled,proto3" json:"dlq_enabled,omitempty"`
	DlqName             string                 `protobuf:"bytes,8,opt,name=dlq_name,json=dlqName,proto3" json:"dlq_name,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueueConfig) Reset() {
	*x = QueueConfig{}
	mi := &file_api_proto_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueConfig) ProtoMessage() {}

func (x *QueueConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueConfig.ProtoReflect.Descriptor instead.
func (*QueueConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{1}
}

func (x *QueueConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QueueConfig) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *QueueConfig) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *QueueConfig) GetMessageTtlMs() int64 {
	if x != nil {
		return x.MessageTtlMs
	}
	return 0
}

func (x *QueueConfig) GetVisibilityTimeoutMs() int64 {
	if x != nil {
		return x.VisibilityTimeoutMs
	}
	return 0
}

func (x *QueueConfig) GetDlqEnabled() bool {
	if x != nil {
		return x.DlqEnabled
	}
	return false
}

func (x *QueueConfig) GetDlqName() string {
	if x != nil {
		return x.DlqName
	}
	return ""
}

// QueueStats represents queue statistics
type QueueStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Length            int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`                                                // Total messages in queue
	Ready             int32                  `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`                                                  // Messages ready for delivery
	Scheduled         int32                  `protobuf:"varint,4,opt,name=scheduled,proto3" json:"scheduled,omitempty"`                                          // Scheduled/delayed messages
	DeliveredCount    int64                  `protobuf:"varint,5,opt,name=delivered_count,json=deliveredCount,proto3" json:"delivered_count,omitempty"`          // Total messages delivered
	AcknowledgedCount int64                  `protobuf:"varint,6,opt,name=acknowledged_count,json=acknowledgedCount,proto3" json:"acknowledged_count,omitempty"` // Total messages acknowledged
	FailedCount       int64                  `protobuf:"varint,7,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`                   // Total failed deliveries
	DlqCount          int32                  `protobuf:"varint,8,opt,name=dlq_count,json=dlqCount,proto3" json:"dlq_count,omitempty"`                            // Messages in dead letter queue
	CreatedAt         int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                         // Unix timestamp in milliseconds
	UpdatedAt         int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                        // Unix timestamp in milliseconds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueueStats) Reset() {
	*x = QueueStats{}
	mi := &file_api_proto_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStats) ProtoMessage() {}

func (x *QueueStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStats.ProtoReflect.Descriptor instead.
func (*QueueStats) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{2}
}

func (x *QueueStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueStats) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *QueueStats) GetReady() int32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *QueueStats) GetScheduled() int32 {
	if x != nil {
		return x.Scheduled
	}
	return 0
}

func (x *QueueStats) GetDeliveredCount() int64 {
	if x != nil {
		return x.DeliveredCount
	}
	return 0
}

func (x *QueueStats) GetAcknowledgedCount() int64 {
	if x != nil {
		return x.AcknowledgedCount
	}
	return 0
}

func (x *QueueStats) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *QueueStats) GetDlqCount() int32 {
	if x != nil {
		return x.DlqCount
	}
	return 0
}

func (x *QueueStats) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *QueueStats) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *QueueConfig           `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueRequest) Reset() {
	*x = CreateQueueRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueRequest) ProtoMessage() {}

func (x *CreateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueRequest.ProtoReflect.Descriptor instead.
func (*CreateQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{3}
}

func (x *CreateQueueRequest) GetConfig() *QueueConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Config        *QueueConfig           `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueResponse) Reset() {
	*x = CreateQueueResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueResponse) ProtoMessage() {}

func (x *CreateQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueResponse.ProtoReflect.Descriptor instead.
func (*CreateQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{4}
}

func (x *CreateQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateQueueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateQueueResponse) GetConfig() *QueueConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueRequest) Reset() {
	*x = DeleteQueueRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueRequest) ProtoMessage() {}

func (x *DeleteQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueRequest.ProtoReflect.Descriptor instead.
func (*DeleteQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteQueueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueResponse) Reset() {
	*x = DeleteQueueResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueResponse) ProtoMessage() {}

func (x *DeleteQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueResponse.ProtoReflect.Descriptor instead.
func (*DeleteQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteQueueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetQueueInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueInfoRequest) Reset() {
	*x = GetQueueInfoRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueInfoRequest) ProtoMessage() {}

func (x *GetQueueInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueInfoRequest.ProtoReflect.Descriptor instead.
func (*GetQueueInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{7}
}

func (x *GetQueueInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetQueueInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *QueueConfig           `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Stats         *QueueStats            `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueInfoResponse) Reset() {
	*x = GetQueueInfoResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueInfoResponse) ProtoMessage() {}

func (x *GetQueueInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueInfoResponse.ProtoReflect.Descriptor instead.
func (*GetQueueInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{8}
}

func (x *GetQueueInfoResponse) GetConfig() *QueueConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetQueueInfoResponse) GetStats() *QueueStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetQueueInfoResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ListQueuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // Filter queues by name prefix
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // Max number of queues to return (0 = unlimited)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesRequest) Reset() {
	*x = ListQueuesRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesRequest) ProtoMessage() {}

func (x *ListQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesRequest.ProtoReflect.Descriptor instead.
func (*ListQueuesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{9}
}

func (x *ListQueuesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListQueuesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListQueuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueNames    []string               `protobuf:"bytes,1,rep,name=queue_names,json=queueNames,proto3" json:"queue_names,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesResponse) Reset() {
	*x = ListQueuesResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesResponse) ProtoMessage() {}

func (x *ListQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesResponse.ProtoReflect.Descriptor instead.
func (*ListQueuesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{10}
}

func (x *ListQueuesResponse) GetQueueNames() []string {
	if x != nil {
		return x.QueueNames
	}
	return nil
}

func (x *ListQueuesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetQueueStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatsRequest) Reset() {
	*x = GetQueueStatsRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatsRequest) ProtoMessage() {}

func (x *GetQueueStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatsRequest.ProtoReflect.Descriptor instead.
func (*GetQueueStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{11}
}

func (x *GetQueueStatsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetQueueStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *QueueStats            `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatsResponse) Reset() {
	*x = GetQueueStatsResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatsResponse) ProtoMessage() {}

func (x *GetQueueStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatsResponse.ProtoReflect.Descriptor instead.
func (*GetQueueStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{12}
}

func (x *GetQueueStatsResponse) GetStats() *QueueStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetQueueStatsResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type PurgeQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeQueueRequest) Reset() {
	*x = PurgeQueueRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeQueueRequest) ProtoMessage() {}

func (x *PurgeQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeQueueRequest.ProtoReflect.Descriptor instead.
func (*PurgeQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{13}
}

func (x *PurgeQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type PurgeQueueResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	MessagesDeleted int32                  `protobuf:"varint,3,opt,name=messages_deleted,json=messagesDeleted,proto3" json:"messages_deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PurgeQueueResponse) Reset() {
	*x = PurgeQueueResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeQueueResponse) ProtoMessage() {}

func (x *PurgeQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeQueueResponse.ProtoReflect.Descriptor instead.
func (*PurgeQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{14}
}

func (x *PurgeQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PurgeQueueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PurgeQueueResponse) GetMessagesDeleted() int32 {
	if x != nil {
		return x.MessagesDeleted
	}
	return 0
}

type EnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"` // Optional, default 0
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ScheduledAt   int64                  `protobuf:"varint,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"` // Unix timestamp in milliseconds (0 = immediate)
	ExpiresAt     int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`       // Unix timestamp in milliseconds (0 = use queue TTL)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{15}
}

func (x *EnqueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *EnqueueRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EnqueueRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EnqueueRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *EnqueueRequest) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *EnqueueRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{16}
}

func (x *EnqueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnqueueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EnqueueResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type DequeueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueRequest) Reset() {
	*x = DequeueRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueRequest) ProtoMessage() {}

func (x *DequeueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueRequest.ProtoReflect.Descriptor instead.
func (*DequeueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{17}
}

func (x *DequeueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type DequeueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueResponse) Reset() {
	*x = DequeueResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueResponse) ProtoMessage() {}

func (x *DequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueResponse.ProtoReflect.Descriptor instead.
func (*DequeueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{18}
}

func (x *DequeueResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *DequeueResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *DequeueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeekRequest) Reset() {
	*x = PeekRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekRequest) ProtoMessage() {}

func (x *PeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeekRequest.ProtoReflect.Descriptor instead.
func (*PeekRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{19}
}

func (x *PeekRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type PeekResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeekResponse) Reset() {
	*x = PeekResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekResponse) ProtoMessage() {}

func (x *PeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeekResponse.ProtoReflect.Descriptor instead.
func (*PeekResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{20}
}

func (x *PeekResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PeekResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *PeekResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AcknowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeRequest) Reset() {
	*x = AcknowledgeRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeRequest) ProtoMessage() {}

func (x *AcknowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{21}
}

func (x *AcknowledgeRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *AcknowledgeRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type AcknowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeResponse) Reset() {
	*x = AcknowledgeResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeResponse) ProtoMessage() {}

func (x *AcknowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{22}
}

func (x *AcknowledgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcknowledgeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Requeue       bool                   `protobuf:"varint,3,opt,name=requeue,proto3" json:"requeue,omitempty"` // If true, requeue the message; if false, delete it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{23}
}

func (x *NackRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *NackRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *NackRequest) GetRequeue() bool {
	if x != nil {
		return x.Requeue
	}
	return false
}

type NackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackResponse) Reset() {
	*x = NackResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackResponse) ProtoMessage() {}

func (x *NackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackResponse.ProtoReflect.Descriptor instead.
func (*NackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{24}
}

func (x *NackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NackResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{25}
}

func (x *GetMessageRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *GetMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GetMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageResponse) Reset() {
	*x = GetMessageResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResponse) ProtoMessage() {}

func (x *GetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResponse.ProtoReflect.Descriptor instead.
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{26}
}

func (x *GetMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *GetMessageResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteMessageRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *DeleteMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchEnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Messages      []*EnqueueRequest      `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEnqueueRequest) Reset() {
	*x = BatchEnqueueRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEnqueueRequest) ProtoMessage() {}

func (x *BatchEnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEnqueueRequest.ProtoReflect.Descriptor instead.
func (*BatchEnqueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{29}
}

func (x *BatchEnqueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *BatchEnqueueRequest) GetMessages() []*EnqueueRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

type BatchEnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*EnqueueResponse     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Successful    int32                  `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEnqueueResponse) Reset() {
	*x = BatchEnqueueResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEnqueueResponse) ProtoMessage() {}

func (x *BatchEnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEnqueueResponse.ProtoReflect.Descriptor instead.
func (*BatchEnqueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{30}
}

func (x *BatchEnqueueResponse) GetResults() []*EnqueueResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchEnqueueResponse) GetSuccessful() int32 {
	if x != nil {
		return x.Successful
	}
	return 0
}

func (x *BatchEnqueueResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type BatchDequeueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // Number of messages to dequeue
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDequeueRequest) Reset() {
	*x = BatchDequeueRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDequeueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDequeueRequest) ProtoMessage() {}

func (x *BatchDequeueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDequeueRequest.ProtoReflect.Descriptor instead.
func (*BatchDequeueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{31}
}

func (x *BatchDequeueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *BatchDequeueRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BatchDequeueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDequeueResponse) Reset() {
	*x = BatchDequeueResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDequeueResponse) ProtoMessage() {}

func (x *BatchDequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDequeueResponse.ProtoReflect.Descriptor instead.
func (*BatchDequeueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{32}
}

func (x *BatchDequeueResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *BatchDequeueResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BatchAcknowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	MessageIds    []string               `protobuf:"bytes,2,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAcknowledgeRequest) Reset() {
	*x = BatchAcknowledgeRequest{}
	mi := &file_api_proto_queue_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAcknowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAcknowledgeRequest) ProtoMessage() {}

func (x *BatchAcknowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAcknowledgeRequest.ProtoReflect.Descriptor instead.
func (*BatchAcknowledgeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{33}
}

func (x *BatchAcknowledgeRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *BatchAcknowledgeRequest) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type BatchAcknowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AcknowledgeResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Successful    int32                  `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAcknowledgeResponse) Reset() {
	*x = BatchAcknowledgeResponse{}
	mi := &file_api_proto_queue_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAcknowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAcknowledgeResponse) ProtoMessage() {}

func (x *BatchAcknowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_queue_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAcknowledgeResponse.ProtoReflect.Descriptor instead.
func (*BatchAcknowledgeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_queue_proto_rawDescGZIP(), []int{34}
}

func (x *BatchAcknowledgeResponse) GetResults() []*AcknowledgeResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchAcknowledgeResponse) GetSuccessful() int32 {
	if x != nil {
		return x.Successful
	}
	return 0
}

func (x *BatchAcknowledgeResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

var File_api_proto_queue_proto protoreflect.FileDescriptor

const file_api_proto_queue_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/queue.proto\x12\akvstore\"\xab\x03\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x127\n" +
	"\aheaders\x18\x05 \x03(\v2\x1d.kvstore.Message.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12!\n" +
	"\fscheduled_at\x18\a \x01(\x03R\vscheduledAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt\x12%\n" +
	"\x0edelivery_count\x18\t \x01(\x05R\rdeliveryCount\x12%\n" +
	"\x0elast_delivered\x18\n" +
	" \x01(\x03R\rlastDelivered\x12\x1d\n" +
	"\n" +
	"dlq_reason\x18\v \x01(\tR\tdlqReason\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x02\n" +
	"\vQueueConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"max_length\x18\x03 \x01(\x05R\tmaxLength\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12$\n" +
	"\x0emessage_ttl_ms\x18\x05 \x01(\x03R\fmessageTtlMs\x122\n" +
	"\x15visibility_timeout_ms\x18\x06 \x01(\x03R\x13visibilityTimeoutMs\x12\x1f\n" +
	"\vdlq_enabled\x18\a \x01(\bR\n" +
	"dlqEnabled\x12\x19\n" +
	"\bdlq_name\x18\b \x01(\tR\adlqName\"\xc2\x02\n" +
	"\n" +
	"QueueStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\x05R\x05ready\x12\x1c\n" +
	"\tscheduled\x18\x04 \x01(\x05R\tscheduled\x12'\n" +
	"\x0fdelivered_count\x18\x05 \x01(\x03R\x0edeliveredCount\x12-\n" +
	"\x12acknowledged_count\x18\x06 \x01(\x03R\x11acknowledgedCount\x12!\n" +
	"\ffailed_count\x18\a \x01(\x03R\vfailedCount\x12\x1b\n" +
	"\tdlq_count\x18\b \x01(\x05R\bdlqCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"B\n" +
	"\x12CreateQueueRequest\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.kvstore.QueueConfigR\x06config\"s\n" +
	"\x13CreateQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12,\n" +
	"\x06config\x18\x03 \x01(\v2\x14.kvstore.QueueConfigR\x06config\"(\n" +
	"\x12DeleteQueueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"E\n" +
	"\x13DeleteQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\x13GetQueueInfoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x85\x01\n" +
	"\x14GetQueueInfoResponse\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.kvstore.QueueConfigR\x06config\x12)\n" +
	"\x05stats\x18\x02 \x01(\v2\x13.kvstore.QueueStatsR\x05stats\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"A\n" +
	"\x11ListQueuesRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"K\n" +
	"\x12ListQueuesResponse\x12\x1f\n" +
	"\vqueue_names\x18\x01 \x03(\tR\n" +
	"queueNames\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"*\n" +
	"\x14GetQueueStatsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"X\n" +
	"\x15GetQueueStatsResponse\x12)\n" +
	"\x05stats\x18\x01 \x01(\v2\x13.kvstore.QueueStatsR\x05stats\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"2\n" +
	"\x11PurgeQueueRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\"o\n" +
	"\x12PurgeQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12)\n" +
	"\x10messages_deleted\x18\x03 \x01(\x05R\x0fmessagesDeleted\"\x9d\x02\n" +
	"\x0eEnqueueRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12>\n" +
	"\aheaders\x18\x04 \x03(\v2$.kvstore.EnqueueRequest.HeadersEntryR\aheaders\x12!\n" +
	"\fscheduled_at\x18\x05 \x01(\x03R\vscheduledAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x0fEnqueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\"/\n" +
	"\x0eDequeueRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\"i\n" +
	"\x0fDequeueResponse\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.kvstore.MessageR\amessage\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\",\n" +
	"\vPeekRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\"f\n" +
	"\fPeekResponse\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.kvstore.MessageR\amessage\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"R\n" +
	"\x12AcknowledgeRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"E\n" +
	"\x13AcknowledgeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"e\n" +
	"\vNackRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x18\n" +
	"\arequeue\x18\x03 \x01(\bR\arequeue\">\n" +
	"\fNackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Q\n" +
	"\x11GetMessageRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"l\n" +
	"\x12GetMessageResponse\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.kvstore.MessageR\amessage\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"T\n" +
	"\x14DeleteMessageRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"G\n" +
	"\x15DeleteMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"i\n" +
	"\x13BatchEnqueueRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x123\n" +
	"\bmessages\x18\x02 \x03(\v2\x17.kvstore.EnqueueRequestR\bmessages\"\x82\x01\n" +
	"\x14BatchEnqueueResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.kvstore.EnqueueResponseR\aresults\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\x05R\n" +
	"successful\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\"J\n" +
	"\x13BatchDequeueRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"Z\n" +
	"\x14BatchDequeueResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.kvstore.MessageR\bmessages\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"Y\n" +
	"\x17BatchAcknowledgeRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\tR\n" +
	"messageIds\"\x8a\x01\n" +
	"\x18BatchAcknowledgeResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.kvstore.AcknowledgeResponseR\aresults\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\x05R\n" +
	"successful\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed2\x87\t\n" +
	"\fQueueService\x12H\n" +
	"\vCreateQueue\x12\x1b.kvstore.CreateQueueRequest\x1a\x1c.kvstore.CreateQueueResponse\x12H\n" +
	"\vDeleteQueue\x12\x1b.kvstore.DeleteQueueRequest\x1a\x1c.kvstore.DeleteQueueResponse\x12K\n" +
	"\fGetQueueInfo\x12\x1c.kvstore.GetQueueInfoRequest\x1a\x1d.kvstore.GetQueueInfoResponse\x12E\n" +
	"\n" +
	"ListQueues\x12\x1a.kvstore.ListQueuesRequest\x1a\x1b.kvstore.ListQueuesResponse\x12N\n" +
	"\rGetQueueStats\x12\x1d.kvstore.GetQueueStatsRequest\x1a\x1e.kvstore.GetQueueStatsResponse\x12E\n" +
	"\n" +
	"PurgeQueue\x12\x1a.kvstore.PurgeQueueRequest\x1a\x1b.kvstore.PurgeQueueResponse\x12<\n" +
	"\aEnqueue\x12\x17.kvstore.EnqueueRequest\x1a\x18.kvstore.EnqueueResponse\x12<\n" +
	"\aDequeue\x12\x17.kvstore.DequeueRequest\x1a\x18.kvstore.DequeueResponse\x123\n" +
	"\x04Peek\x12\x14.kvstore.PeekRequest\x1a\x15.kvstore.PeekResponse\x12H\n" +
	"\vAcknowledge\x12\x1b.kvstore.AcknowledgeRequest\x1a\x1c.kvstore.AcknowledgeResponse\x123\n" +
	"\x04Nack\x12\x14.kvstore.NackRequest\x1a\x15.kvstore.NackResponse\x12E\n" +
	"\n" +
	"GetMessage\x12\x1a.kvstore.GetMessageRequest\x1a\x1b.kvstore.GetMessageResponse\x12N\n" +
	"\rDeleteMessage\x12\x1d.kvstore.DeleteMessageRequest\x1a\x1e.kvstore.DeleteMessageResponse\x12K\n" +
	"\fBatchEnqueue\x12\x1c.kvstore.BatchEnqueueRequest\x1a\x1d.kvstore.BatchEnqueueResponse\x12K\n" +
	"\fBatchDequeue\x12\x1c.kvstore.BatchDequeueRequest\x1a\x1d.kvstore.BatchDequeueResponse\x12W\n" +
	"\x10BatchAcknowledge\x12 .kvstore.BatchAcknowledgeRequest\x1a!.kvstore.BatchAcknowledgeResponseB/Z-github.com/RashikAnsar/raftkv/api/proto;protob\x06proto3"

var (
	file_api_proto_queue_proto_rawDescOnce sync.Once
	file_api_proto_queue_proto_rawDescData []byte
)

func file_api_proto_queue_proto_rawDescGZIP() []byte {
	file_api_proto_queue_proto_rawDescOnce.Do(func() {
		file_api_proto_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_queue_proto_rawDesc), len(file_api_proto_queue_proto_rawDesc)))
	})
	return file_api_proto_queue_proto_rawDescData
}

var file_api_proto_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_api_proto_queue_proto_goTypes = []any{
	(*Message)(nil),                  // 0: kvstore.Message
	(*QueueConfig)(nil),              // 1: kvstore.QueueConfig
	(*QueueStats)(nil),               // 2: kvstore.QueueStats
	(*CreateQueueRequest)(nil),       // 3: kvstore.CreateQueueRequest
	(*CreateQueueResponse)(nil),      // 4: kvstore.CreateQueueResponse
	(*DeleteQueueRequest)(nil),       // 5: kvstore.DeleteQueueRequest
	(*DeleteQueueResponse)(nil),      // 6: kvstore.DeleteQueueResponse
	(*GetQueueInfoRequest)(nil),      // 7: kvstore.GetQueueInfoRequest
	(*GetQueueInfoResponse)(nil),     // 8: kvstore.GetQueueInfoResponse
	(*ListQueuesRequest)(nil),        // 9: kvstore.ListQueuesRequest
	(*ListQueuesResponse)(nil),       // 10: kvstore.ListQueuesResponse
	(*GetQueueStatsRequest)(nil),     // 11: kvstore.GetQueueStatsRequest
	(*GetQueueStatsResponse)(nil),    // 12: kvstore.GetQueueStatsResponse
	(*PurgeQueueRequest)(nil),        // 13: kvstore.PurgeQueueRequest
	(*PurgeQueueResponse)(nil),       // 14: kvstore.PurgeQueueResponse
	(*EnqueueRequest)(nil),           // 15: kvstore.EnqueueRequest
	(*EnqueueResponse)(nil),          // 16: kvstore.EnqueueResponse
	(*DequeueRequest)(nil),           // 17: kvstore.DequeueRequest
	(*DequeueResponse)(nil),          // 18: kvstore.DequeueResponse
	(*PeekRequest)(nil),              // 19: kvstore.PeekRequest
	(*PeekResponse)(nil),             // 20: kvstore.PeekResponse
	(*AcknowledgeRequest)(nil),       // 21: kvstore.AcknowledgeRequest
	(*AcknowledgeResponse)(nil),      // 22: kvstore.AcknowledgeResponse
	(*NackRequest)(nil),              // 23: kvstore.NackRequest
	(*NackResponse)(nil),             // 24: kvstore.NackResponse
	(*GetMessageRequest)(nil),        // 25: kvstore.GetMessageRequest
	(*GetMessageResponse)(nil),       // 26: kvstore.GetMessageResponse
	(*DeleteMessageRequest)(nil),     // 27: kvstore.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),    // 28: kvstore.DeleteMessageResponse
	(*BatchEnqueueRequest)(nil),      // 29: kvstore.BatchEnqueueRequest
	(*BatchEnqueueResponse)(nil),     // 30: kvstore.BatchEnqueueResponse
	(*BatchDequeueRequest)(nil),      // 31: kvstore.BatchDequeueRequest
	(*BatchDequeueResponse)(nil),     // 32: kvstore.BatchDequeueResponse
	(*BatchAcknowledgeRequest)(nil),  // 33: kvstore.BatchAcknowledgeRequest
	(*BatchAcknowledgeResponse)(nil), // 34: kvstore.BatchAcknowledgeResponse
	nil,                              // 35: kvstore.Message.HeadersEntry
	nil,                              // 36: kvstore.EnqueueRequest.HeadersEntry
}
var file_api_proto_queue_proto_depIdxs = []int32{
	35, // 0: kvstore.Message.headers:type_name -> kvstore.Message.HeadersEntry
	1,  // 1: kvstore.CreateQueueRequest.config:type_name -> kvstore.QueueConfig
	1,  // 2: kvstore.CreateQueueResponse.config:type_name -> kvstore.QueueConfig
	1,  // 3: kvstore.GetQueueInfoResponse.config:type_name -> kvstore.QueueConfig
	2,  // 4: kvstore.GetQueueInfoResponse.stats:type_name -> kvstore.QueueStats
	2,  // 5: kvstore.GetQueueStatsResponse.stats:type_name -> kvstore.QueueStats
	36, // 6: kvstore.EnqueueRequest.headers:type_name -> kvstore.EnqueueRequest.HeadersEntry
	0,  // 7: kvstore.DequeueResponse.message:type_name -> kvstore.Message
	0,  // 8: kvstore.PeekResponse.message:type_name -> kvstore.Message
	0,  // 9: kvstore.GetMessageResponse.message:type_name -> kvstore.Message
	15, // 10: kvstore.BatchEnqueueRequest.messages:type_name -> kvstore.EnqueueRequest
	16, // 11: kvstore.BatchEnqueueResponse.results:type_name -> kvstore.EnqueueResponse
	0,  // 12: kvstore.BatchDequeueResponse.messages:type_name -> kvstore.Message
	22, // 13: kvstore.BatchAcknowledgeResponse.results:type_name -> kvstore.AcknowledgeResponse
	3,  // 14: kvstore.QueueService.CreateQueue:input_type -> kvstore.CreateQueueRequest
	5,  // 15: kvstore.QueueService.DeleteQueue:input_type -> kvstore.DeleteQueueRequest
	7,  // 16: kvstore.QueueService.GetQueueInfo:input_type -> kvstore.GetQueueInfoRequest
	9,  // 17: kvstore.QueueService.ListQueues:input_type -> kvstore.ListQueuesRequest
	11, // 18: kvstore.QueueService.GetQueueStats:input_type -> kvstore.GetQueueStatsRequest
	13, // 19: kvstore.QueueService.PurgeQueue:input_type -> kvstore.PurgeQueueRequest
	15, // 20: kvstore.QueueService.Enqueue:input_type -> kvstore.EnqueueRequest
	17, // 21: kvstore.QueueService.Dequeue:input_type -> kvstore.DequeueRequest
	19, // 22: kvstore.QueueService.Peek:input_type -> kvstore.PeekRequest
	21, // 23: kvstore.QueueService.Acknowledge:input_type -> kvstore.AcknowledgeRequest
	23, // 24: kvstore.QueueService.Nack:input_type -> kvstore.NackRequest
	25, // 25: kvstore.QueueService.GetMessage:input_type -> kvstore.GetMessageRequest
	27, // 26: kvstore.QueueService.DeleteMessage:input_type -> kvstore.DeleteMessageRequest
	29, // 27: kvstore.QueueService.BatchEnqueue:input_type -> kvstore.BatchEnqueueRequest
	31, // 28: kvstore.QueueService.BatchDequeue:input_type -> kvstore.BatchDequeueRequest
	33, // 29: kvstore.QueueService.BatchAcknowledge:input_type -> kvstore.BatchAcknowledgeRequest
	4,  // 30: kvstore.QueueService.CreateQueue:output_type -> kvstore.CreateQueueResponse
	6,  // 31: kvstore.QueueService.DeleteQueue:output_type -> kvstore.DeleteQueueResponse
	8,  // 32: kvstore.QueueService.GetQueueInfo:output_type -> kvstore.GetQueueInfoResponse
	10, // 33: kvstore.QueueService.ListQueues:output_type -> kvstore.ListQueuesResponse
	12, // 34: kvstore.QueueService.GetQueueStats:output_type -> kvstore.GetQueueStatsResponse
	14, // 35: kvstore.QueueService.PurgeQueue:output_type -> kvstore.PurgeQueueResponse
	16, // 36: kvstore.QueueService.Enqueue:output_type -> kvstore.EnqueueResponse
	18, // 37: kvstore.QueueService.Dequeue:output_type -> kvstore.DequeueResponse
	20, // 38: kvstore.QueueService.Peek:output_type -> kvstore.PeekResponse
	22, // 39: kvstore.QueueService.Acknowledge:output_type -> kvstore.AcknowledgeResponse
	24, // 40: kvstore.QueueService.Nack:output_type -> kvstore.NackResponse
	26, // 41: kvstore.QueueService.GetMessage:output_type -> kvstore.GetMessageResponse
	28, // 42: kvstore.QueueService.DeleteMessage:output_type -> kvstore.DeleteMessageResponse
	30, // 43: kvstore.QueueService.BatchEnqueue:output_type -> kvstore.BatchEnqueueResponse
	32, // 44: kvstore.QueueService.BatchDequeue:output_type -> kvstore.BatchDequeueResponse
	34, // 45: kvstore.QueueService.BatchAcknowledge:output_type -> kvstore.BatchAcknowledgeResponse
	30, // [30:46] is the sub-list for method output_type
	14, // [14:30] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_queue_proto_init() }
func file_api_proto_queue_proto_init() {
	if File_api_proto_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_queue_proto_rawDesc), len(file_api_proto_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_queue_proto_goTypes,
		DependencyIndexes: file_api_proto_queue_proto_depIdxs,
		MessageInfos:      file_api_proto_queue_proto_msgTypes,
	}.Build()
	File_api_proto_queue_proto = out.File
	file_api_proto_queue_proto_goTypes = nil
	file_api_proto_queue_proto_depIdxs = nil
}
