// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/replication.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthStatus represents overall replication health
type HealthStatus int32

const (
	HealthStatus_HEALTH_UNKNOWN   HealthStatus = 0
	HealthStatus_HEALTH_HEALTHY   HealthStatus = 1
	HealthStatus_HEALTH_DEGRADED  HealthStatus = 2
	HealthStatus_HEALTH_UNHEALTHY HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_UNKNOWN",
		1: "HEALTH_HEALTHY",
		2: "HEALTH_DEGRADED",
		3: "HEALTH_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_UNKNOWN":   0,
		"HEALTH_HEALTHY":   1,
		"HEALTH_DEGRADED":  2,
		"HEALTH_UNHEALTHY": 3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_replication_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_api_proto_replication_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_replication_proto_rawDescGZIP(), []int{0}
}

// StreamRequest specifies parameters for change streaming
type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Starting Raft index (exclusive) - stream events after this index
	FromIndex uint64 `protobuf:"varint,1,opt,name=from_index,json=fromIndex,proto3" json:"from_index,omitempty"`
	// Datacenter ID of the requesting DC
	DatacenterId string `protobuf:"bytes,2,opt,name=datacenter_id,json=datacenterId,proto3" json:"datacenter_id,omitempty"`
	// Optional key prefix filter
	KeyPrefix string `protobuf:"bytes,3,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	// Batch size for streaming (0 = default)
	BatchSize     int32 `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_api_proto_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetFromIndex() uint64 {
	if x != nil {
		return x.FromIndex
	}
	return 0
}

func (x *StreamRequest) GetDatacenterId() string {
	if x != nil {
		return x.DatacenterId
	}
	return ""
}

func (x *StreamRequest) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *StreamRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

// ChangeEvent represents a single change in the key-value store
type ChangeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raft metadata
	RaftIndex uint64 `protobuf:"varint,1,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	RaftTerm  uint64 `protobuf:"varint,2,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	// Operation type: "put" or "delete"
	Operation string `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	// Key-value data
	Key   string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	// Timestamp when the change occurred
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Source datacenter ID
	DatacenterId string `protobuf:"bytes,7,opt,name=datacenter_id,json=datacenterId,proto3" json:"datacenter_id,omitempty"`
	// CDC sequence number
	SequenceNum uint64 `protobuf:"varint,8,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	// Vector clock for conflict resolution (map of DC ID -> logical clock)
	VectorClock   map[string]uint64 `protobuf:"bytes,9,rep,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	mi := &file_api_proto_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_replication_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeEvent) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

func (x *ChangeEvent) GetRaftTerm() uint64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

func (x *ChangeEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ChangeEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChangeEvent) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ChangeEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ChangeEvent) GetDatacenterId() string {
	if x != nil {
		return x.DatacenterId
	}
	return ""
}

func (x *ChangeEvent) GetSequenceNum() uint64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *ChangeEvent) GetVectorClock() map[string]uint64 {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

// StatusRequest for querying replication status
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Datacenter ID to check status for (empty = all)
	DatacenterId  string `protobuf:"bytes,1,opt,name=datacenter_id,json=datacenterId,proto3" json:"datacenter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_replication_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetDatacenterId() string {
	if x != nil {
		return x.DatacenterId
	}
	return ""
}

// ReplicationStatus describes the current replication state
type ReplicationStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current datacenter ID
	DatacenterId string `protobuf:"bytes,1,opt,name=datacenter_id,json=datacenterId,proto3" json:"datacenter_id,omitempty"`
	// Last applied Raft index
	LastIndex uint64 `protobuf:"varint,2,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	// Last applied Raft term
	LastTerm uint64 `protobuf:"varint,3,opt,name=last_term,json=lastTerm,proto3" json:"last_term,omitempty"`
	// Replication lag per target DC
	LagByDc map[string]*DatacenterLag `protobuf:"bytes,4,rep,name=lag_by_dc,json=lagByDc,proto3" json:"lag_by_dc,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Overall health status
	Health HealthStatus `protobuf:"varint,5,opt,name=health,proto3,enum=proto.HealthStatus" json:"health,omitempty"`
	// Total events replicated
	EventsReplicated uint64 `protobuf:"varint,6,opt,name=events_replicated,json=eventsReplicated,proto3" json:"events_replicated,omitempty"`
	// Total events dropped
	EventsDropped uint64 `protobuf:"varint,7,opt,name=events_dropped,json=eventsDropped,proto3" json:"events_dropped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationStatus) Reset() {
	*x = ReplicationStatus{}
	mi := &file_api_proto_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationStatus) ProtoMessage() {}

func (x *ReplicationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationStatus.ProtoReflect.Descriptor instead.
func (*ReplicationStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_replication_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicationStatus) GetDatacenterId() string {
	if x != nil {
		return x.DatacenterId
	}
	return ""
}

func (x *ReplicationStatus) GetLastIndex() uint64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

func (x *ReplicationStatus) GetLastTerm() uint64 {
	if x != nil {
		return x.LastTerm
	}
	return 0
}

func (x *ReplicationStatus) GetLagByDc() map[string]*DatacenterLag {
	if x != nil {
		return x.LagByDc
	}
	return nil
}

func (x *ReplicationStatus) GetHealth() HealthStatus {
	if x != nil {
		return x.Health
	}
	return HealthStatus_HEALTH_UNKNOWN
}

func (x *ReplicationStatus) GetEventsReplicated() uint64 {
	if x != nil {
		return x.EventsReplicated
	}
	return 0
}

func (x *ReplicationStatus) GetEventsDropped() uint64 {
	if x != nil {
		return x.EventsDropped
	}
	return 0
}

// DatacenterLag describes replication lag to a specific DC
type DatacenterLag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target datacenter ID
	DatacenterId string `protobuf:"bytes,1,opt,name=datacenter_id,json=datacenterId,proto3" json:"datacenter_id,omitempty"`
	// Last replicated index to this DC
	LastReplicatedIndex uint64 `protobuf:"varint,2,opt,name=last_replicated_index,json=lastReplicatedIndex,proto3" json:"last_replicated_index,omitempty"`
	// Lag in number of entries
	LagEntries uint64 `protobuf:"varint,3,opt,name=lag_entries,json=lagEntries,proto3" json:"lag_entries,omitempty"`
	// Estimated lag in seconds
	LagSeconds float64 `protobuf:"fixed64,4,opt,name=lag_seconds,json=lagSeconds,proto3" json:"lag_seconds,omitempty"`
	// Connection status
	Connected bool `protobuf:"varint,5,opt,name=connected,proto3" json:"connected,omitempty"`
	// Last successful replication timestamp
	LastSuccess   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_success,json=lastSuccess,proto3" json:"last_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatacenterLag) Reset() {
	*x = DatacenterLag{}
	mi := &file_api_proto_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatacenterLag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatacenterLag) ProtoMessage() {}

func (x *DatacenterLag) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatacenterLag.ProtoReflect.Descriptor instead.
func (*DatacenterLag) Descriptor() ([]byte, []int) {
	return file_api_proto_replication_proto_rawDescGZIP(), []int{4}
}

func (x *DatacenterLag) GetDatacenterId() string {
	if x != nil {
		return x.DatacenterId
	}
	return ""
}

func (x *DatacenterLag) GetLastReplicatedIndex() uint64 {
	if x != nil {
		return x.LastReplicatedIndex
	}
	return 0
}

func (x *DatacenterLag) GetLagEntries() uint64 {
	if x != nil {
		return x.LagEntries
	}
	return 0
}

func (x *DatacenterLag) GetLagSeconds() float64 {
	if x != nil {
		return x.LagSeconds
	}
	return 0
}

func (x *DatacenterLag) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *DatacenterLag) GetLastSuccess() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccess
	}
	return nil
}

// HeartbeatRequest for connection health checking
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatacenterId  string                 `protobuf:"bytes,1,opt,name=datacenter_id,json=datacenterId,proto3" json:"datacenter_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_replication_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetDatacenterId() string {
	if x != nil {
		return x.DatacenterId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// HeartbeatResponse confirms connection is alive
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatacenterId  string                 `protobuf:"bytes,1,opt,name=datacenter_id,json=datacenterId,proto3" json:"datacenter_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Health        HealthStatus           `protobuf:"varint,3,opt,name=health,proto3,enum=proto.HealthStatus" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_replication_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetDatacenterId() string {
	if x != nil {
		return x.DatacenterId
	}
	return ""
}

func (x *HeartbeatResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatResponse) GetHealth() HealthStatus {
	if x != nil {
		return x.Health
	}
	return HealthStatus_HEALTH_UNKNOWN
}

var File_api_proto_replication_proto protoreflect.FileDescriptor

const file_api_proto_replication_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/replication.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x01\n" +
	"\rStreamRequest\x12\x1d\n" +
	"\n" +
	"from_index\x18\x01 \x01(\x04R\tfromIndex\x12#\n" +
	"\rdatacenter_id\x18\x02 \x01(\tR\fdatacenterId\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x03 \x01(\tR\tkeyPrefix\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x05R\tbatchSize\"\x99\x03\n" +
	"\vChangeEvent\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x01 \x01(\x04R\traftIndex\x12\x1b\n" +
	"\traft_term\x18\x02 \x01(\x04R\braftTerm\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\rdatacenter_id\x18\a \x01(\tR\fdatacenterId\x12!\n" +
	"\fsequence_num\x18\b \x01(\x04R\vsequenceNum\x12F\n" +
	"\fvector_clock\x18\t \x03(\v2#.proto.ChangeEvent.VectorClockEntryR\vvectorClock\x1a>\n" +
	"\x10VectorClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"4\n" +
	"\rStatusRequest\x12#\n" +
	"\rdatacenter_id\x18\x01 \x01(\tR\fdatacenterId\"\x8a\x03\n" +
	"\x11ReplicationStatus\x12#\n" +
	"\rdatacenter_id\x18\x01 \x01(\tR\fdatacenterId\x12\x1d\n" +
	"\n" +
	"last_index\x18\x02 \x01(\x04R\tlastIndex\x12\x1b\n" +
	"\tlast_term\x18\x03 \x01(\x04R\blastTerm\x12A\n" +
	"\tlag_by_dc\x18\x04 \x03(\v2%.proto.ReplicationStatus.LagByDcEntryR\alagByDc\x12+\n" +
	"\x06health\x18\x05 \x01(\x0e2\x13.proto.HealthStatusR\x06health\x12+\n" +
	"\x11events_replicated\x18\x06 \x01(\x04R\x10eventsReplicated\x12%\n" +
	"\x0eevents_dropped\x18\a \x01(\x04R\reventsDropped\x1aP\n" +
	"\fLagByDcEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.proto.DatacenterLagR\x05value:\x028\x01\"\x87\x02\n" +
	"\rDatacenterLag\x12#\n" +
	"\rdatacenter_id\x18\x01 \x01(\tR\fdatacenterId\x122\n" +
	"\x15last_replicated_index\x18\x02 \x01(\x04R\x13lastReplicatedIndex\x12\x1f\n" +
	"\vlag_entries\x18\x03 \x01(\x04R\n" +
	"lagEntries\x12\x1f\n" +
	"\vlag_seconds\x18\x04 \x01(\x01R\n" +
	"lagSeconds\x12\x1c\n" +
	"\tconnected\x18\x05 \x01(\bR\tconnected\x12=\n" +
	"\flast_success\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vlastSuccess\"q\n" +
	"\x10HeartbeatRequest\x12#\n" +
	"\rdatacenter_id\x18\x01 \x01(\tR\fdatacenterId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x9f\x01\n" +
	"\x11HeartbeatResponse\x12#\n" +
	"\rdatacenter_id\x18\x01 \x01(\tR\fdatacenterId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x06health\x18\x03 \x01(\x0e2\x13.proto.HealthStatusR\x06health*a\n" +
	"\fHealthStatus\x12\x12\n" +
	"\x0eHEALTH_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x01\x12\x13\n" +
	"\x0fHEALTH_DEGRADED\x10\x02\x12\x14\n" +
	"\x10HEALTH_UNHEALTHY\x10\x032\xd9\x01\n" +
	"\x12ReplicationService\x12;\n" +
	"\rStreamChanges\x12\x14.proto.StreamRequest\x1a\x12.proto.ChangeEvent0\x01\x12F\n" +
	"\x14GetReplicationStatus\x12\x14.proto.StatusRequest\x1a\x18.proto.ReplicationStatus\x12>\n" +
	"\tHeartbeat\x12\x17.proto.HeartbeatRequest\x1a\x18.proto.HeartbeatResponseB)Z'github.com/RashikAnsar/raftkv/api/protob\x06proto3"

var (
	file_api_proto_replication_proto_rawDescOnce sync.Once
	file_api_proto_replication_proto_rawDescData []byte
)

func file_api_proto_replication_proto_rawDescGZIP() []byte {
	file_api_proto_replication_proto_rawDescOnce.Do(func() {
		file_api_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_replication_proto_rawDesc), len(file_api_proto_replication_proto_rawDesc)))
	})
	return file_api_proto_replication_proto_rawDescData
}

var file_api_proto_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_replication_proto_goTypes = []any{
	(HealthStatus)(0),             // 0: proto.HealthStatus
	(*StreamRequest)(nil),         // 1: proto.StreamRequest
	(*ChangeEvent)(nil),           // 2: proto.ChangeEvent
	(*StatusRequest)(nil),         // 3: proto.StatusRequest
	(*ReplicationStatus)(nil),     // 4: proto.ReplicationStatus
	(*DatacenterLag)(nil),         // 5: proto.DatacenterLag
	(*HeartbeatRequest)(nil),      // 6: proto.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 7: proto.HeartbeatResponse
	nil,                           // 8: proto.ChangeEvent.VectorClockEntry
	nil,                           // 9: proto.ReplicationStatus.LagByDcEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_api_proto_replication_proto_depIdxs = []int32{
	10, // 0: proto.ChangeEvent.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 1: proto.ChangeEvent.vector_clock:type_name -> proto.ChangeEvent.VectorClockEntry
	9,  // 2: proto.ReplicationStatus.lag_by_dc:type_name -> proto.ReplicationStatus.LagByDcEntry
	0,  // 3: proto.ReplicationStatus.health:type_name -> proto.HealthStatus
	10, // 4: proto.DatacenterLag.last_success:type_name -> google.protobuf.Timestamp
	10, // 5: proto.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	10, // 6: proto.HeartbeatResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 7: proto.HeartbeatResponse.health:type_name -> proto.HealthStatus
	5,  // 8: proto.ReplicationStatus.LagByDcEntry.value:type_name -> proto.DatacenterLag
	1,  // 9: proto.ReplicationService.StreamChanges:input_type -> proto.StreamRequest
	3,  // 10: proto.ReplicationService.GetReplicationStatus:input_type -> proto.StatusRequest
	6,  // 11: proto.ReplicationService.Heartbeat:input_type -> proto.HeartbeatRequest
	2,  // 12: proto.ReplicationService.StreamChanges:output_type -> proto.ChangeEvent
	4,  // 13: proto.ReplicationService.GetReplicationStatus:output_type -> proto.ReplicationStatus
	7,  // 14: proto.ReplicationService.Heartbeat:output_type -> proto.HeartbeatResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_replication_proto_init() }
func file_api_proto_replication_proto_init() {
	if File_api_proto_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_replication_proto_rawDesc), len(file_api_proto_replication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_replication_proto_goTypes,
		DependencyIndexes: file_api_proto_replication_proto_depIdxs,
		EnumInfos:         file_api_proto_replication_proto_enumTypes,
		MessageInfos:      file_api_proto_replication_proto_msgTypes,
	}.Build()
	File_api_proto_replication_proto = out.File
	file_api_proto_replication_proto_goTypes = nil
	file_api_proto_replication_proto_depIdxs = nil
}
